n = int(input('Ingrese un número para calcular sus porcentajes: '))
cal =((n*20)/100)
cal2 =((n*60)/100)
cal3 =((n*90)/100)

print ("Calculadora 20%, 60%, 90%")
print ("--------------------------------------")
print ()
print ("El 20% de su número es: ", (cal))
print ()
print ("El 60% de su número es: ", (cal2))
print()
print ("El 90% de su número es: ", (cal3))
print ()